services:
  mysql:
    image: mysql
    container_name: mysql-micronaut
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - micronaut_db:/var/lib/mysql

volumes:
  micronaut_db: